# Generated by Django 5.1.3 on 2026-04-20 06:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('google_id', models.CharField(blank=True, help_text='Google OAuth ID for single sign-on authentication', max_length=100, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Designates whether this user has been approved by an OWNER. Unapproved users cannot access the system.')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS', 'Operations'), ('CASHIER', 'Cashier'), ('DELIVERY', 'Delivery'), ('CUSTOMER', 'Customer')], default='CUSTOMER', help_text='User role determining system access permissions', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user account was created')),
                ('last_login', models.DateTimeField(blank=True, help_text="Date and time of the user's last login", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=100)),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('avatar_url', models.URLField(blank=True, help_text="URL to user's profile picture")),
                ('notification_preferences', models.JSONField(default=dict, help_text='User notification preferences in JSON format')),
                ('google_locale', models.CharField(blank=True, help_text='Language/locale returned by Google (e.g. "en")', max_length=10)),
                ('google_hd', models.CharField(blank=True, help_text='Google Workspace hosted domain (e.g. "company.com"), empty for personal accounts', max_length=255)),
                ('google_verified_email', models.BooleanField(blank=True, help_text='Whether Google has verified this email address', null=True)),
                ('google_raw_metadata', models.JSONField(blank=True, default=dict, help_text='Full Google ID token payload stored for future use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['google_id'], name='auth_user_google__39783d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='auth_user_role_f90fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_approved'], name='auth_user_is_appr_aeda61_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='auth_user_created_2cecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_4f95f8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone'], name='user_profil_phone_0e28bf_idx'),
        ),
    ]
