# Generated by Django 5.1.3 on 2026-04-20 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (e.g., CREATE, UPDATE, DELETE)', max_length=100)),
                ('table_name', models.CharField(blank=True, help_text='Database table affected', max_length=100)),
                ('record_id', models.IntegerField(blank=True, help_text='ID of the affected record', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['action'], name='audit_log_action_b32d4d_idx'), models.Index(fields=['table_name', 'record_id'], name='audit_log_table_n_38ccfb_idx'), models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('ORDER_STATUS', 'Order Status Update'), ('USER_APPROVAL', 'User Approval Request'), ('USER_APPROVED', 'User Account Approved'), ('USER_REJECTED', 'User Account Rejected'), ('RETURN_CREATED', 'Return Created'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_PROCESSED', 'Return Processed'), ('SYSTEM_ALERT', 'System Alert'), ('GENERAL', 'General Notification')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('data', models.JSONField(default=dict, help_text='Additional notification data in JSON format')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Whether email notification has been sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Date and time when email was sent', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Notification priority level', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date and time when notification expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_ca50c0_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f8d066_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_8a483f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_86bdfc_idx'), models.Index(fields=['created_at'], name='notificatio_created_db7ad3_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_6c5b53_idx')],
            },
        ),
    ]
