# Generated by Django 5.1.3 on 2026-04-20 06:40

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(
                        help_text="Unique return number (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PROCESSED", "Processed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Current return status",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_method",
                    models.CharField(
                        choices=[
                            ("REFUND", "Refund"),
                            ("CREDIT", "Store Credit"),
                            ("EXCHANGE", "Exchange"),
                        ],
                        default="REFUND",
                        help_text="How the return will be resolved",
                        max_length=20,
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        blank=True, help_text="Reason for return", max_length=100
                    ),
                ),
                (
                    "return_reason_details",
                    models.TextField(
                        blank=True, help_text="Detailed explanation of return reason"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount of items being returned",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount to be credited to customer account",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount to be refunded to customer",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restocking_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Restocking fee charged",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional return notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when return was approved",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when return was processed",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer making the return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original order being returned",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="orders.customerorder",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who processed this return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Return",
                "verbose_name_plural": "Customer Returns",
                "db_table": "customer_return",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        help_text="Barcode of the item (stored for audit trail)",
                        max_length=100,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item (stored for audit trail)",
                        max_length=200,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity being returned",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price from original order",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total price for this return item",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("USED", "Used"),
                            ("DAMAGED", "Damaged"),
                            ("DEFECTIVE", "Defective"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Condition of returned item",
                        max_length=50,
                    ),
                ),
                (
                    "restockable",
                    models.BooleanField(
                        default=True, help_text="Whether this item can be restocked"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="Original order item being returned",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "return_obj",
                    models.ForeignKey(
                        help_text="Return this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.customerreturn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Item",
                "verbose_name_plural": "Return Items",
                "db_table": "return_item",
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")],
                        help_text="Type of credit transaction",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credit balance before transaction",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Credit balance after transaction",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RETURN", "Return"),
                            ("ORDER", "Order"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("REFUND", "Refund"),
                        ],
                        help_text="Type of reference document",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, help_text="ID of reference document", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Transaction description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Transaction",
                "verbose_name_plural": "Credit Transactions",
                "db_table": "credit_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer"], name="credit_tran_custome_301d0e_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="credit_tran_transac_b37c51_idx",
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="credit_tran_referen_ef5ca7_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="credit_tran_created_210f9e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current credit balance",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total credits earned",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total credits used",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        help_text="Customer this credit account belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Credit",
                "verbose_name_plural": "Customer Credits",
                "db_table": "customer_credit",
                "indexes": [
                    models.Index(
                        fields=["customer"], name="customer_cr_custome_0a548a_idx"
                    ),
                    models.Index(
                        fields=["balance"], name="customer_cr_balance_da702e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(
                fields=["return_number"], name="customer_re_return__2c3347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(fields=["order"], name="customer_re_order_i_9a92a8_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(
                fields=["customer"], name="customer_re_custome_6a148d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(fields=["status"], name="customer_re_status_64d4b8_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(
                fields=["created_at"], name="customer_re_created_a7e32c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(
                fields=["processed_by"], name="customer_re_process_727a99_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credit_amount__gte", 0),
                    ("refund_amount__gte", 0),
                    (
                        "credit_amount__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_amount"), "+", models.F("restocking_fee")
                        ),
                    ),
                    (
                        "refund_amount__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("total_amount"), "+", models.F("restocking_fee")
                        ),
                    ),
                ),
                name="valid_return_amounts",
            ),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(
                fields=["return_obj"], name="return_item_return__b2a598_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(
                fields=["order_item"], name="return_item_order_i_cc55e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnitem",
            index=models.Index(
                fields=["barcode"], name="return_item_barcode_7fa708_idx"
            ),
        ),
    ]
