# Generated by Django 5.1.3 on 2026-04-20 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorycategory')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'inventory_category',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Unique barcode identifier (required for all operations)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must contain only alphanumeric characters and hyphens', regex='^[0-9A-Za-z\\-]+$')])),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed item description')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock_level', models.IntegerField(default=10, help_text='Minimum stock level for low stock alerts', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_stock_level', models.IntegerField(blank=True, help_text='Maximum stock level (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Item category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment')], help_text='Type of stock transaction', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity involved in transaction', validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_stock', models.IntegerField(help_text='Stock quantity before transaction', validators=[django.core.validators.MinValueValidator(0)])),
                ('new_stock', models.IntegerField(help_text='Stock quantity after transaction', validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_type', models.CharField(blank=True, choices=[('ORDER', 'Order'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Manual Adjustment'), ('INITIAL', 'Initial Stock')], help_text='Type of reference document', max_length=20, null=True)),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of reference document', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'db_table': 'stock_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['parent'], name='inventory_c_parent__a38b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_i_categor_dcc1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['stock_quantity'], name='inventory_i_stock_q_46db23_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['min_stock_level'], name='inventory_i_min_sto_303d22_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_fd4174_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['created_by'], name='inventory_i_created_a8d6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['created_at'], name='inventory_i_created_875751_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('max_stock_level__isnull', True), ('max_stock_level__gte', models.F('min_stock_level')), _connector='OR'), name='max_stock_gte_min_stock'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item'], name='stock_trans_item_id_6d5937_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_trans_transac_c3f401_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='stock_trans_referen_49a510_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='stock_trans_created_ece84f_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_by'], name='stock_trans_created_040945_idx'),
        ),
    ]
